apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-jtwe
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-jtwe
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-jtwe
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-jtwe
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-jtwe
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-chgy-tenant/rhtap-demo-app/hacbs-test-project-jtwe@sha256:38b66d62c70720f3482815aaad5799f2f49d09b80ba1eefcb46523598aaf7f56
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
